name: Android CI

on: 
  push:
    branches:
      - master
jobs:
  build:    
    runs-on: ubuntu-latest
    env: 
      NODE_ENV: test 
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        age: '1 day'
        skip-tags: true  
    - name: Add ChMOD
      run: chmod +x gradlew
    - name: Test
      run: sudo ./gradlew test --stacktrace
    - name: Build debug APK
      run: sudo ./gradlew assembleDebug --stacktrace
    
#     - name: Coveralls Parallel
#       uses: coverallsapp/github-action@master
#       with:
#         github-token: ${{ secrets.GITHUB_TOKEN }}
#         parallel: true
#         path-to-lcov: ./coverage/lcov.info # optional (default value)
#    - name: Upload APK
 #     uses: actions/upload-artifact@v1
  #    with:
   #     name: app
    #    path: app/build/outputs/apk/debug/app-debug.apk

 
