dist: trusty
group: edge
language: python
sudo: required
services:
        - docker
before_install:
        - docker pull rethinkdb
        - docker pull osixia/openldap
        - docker-compose -f tests/docker-compose.yml up -d rethinkdb ldap
install:
        - pip install -r requirements.txt
script: python -m pytest
