version: '3'
services:
  postgresql-1-postgresql-svc:
    image: postgres
    container_name: postgres-server
    restart: unless-stopped
    tty: true
    environment:
      POSTGRES_PASSWORD: password
      # ports:
      #- 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-network
  rethinkdb-proxy:
    image: rethinkdb
    container_name: rethinkdb-server
    restart: unless-stopped
    tty: true
    ports:
      #- 28015:28015
      - 8080:8080
    volumes:
      - rethink-data:/var/lib/rethinkdb/data
    networks:
      - backend-network
  stalker-backend:
    build: .
    #image: jjocram/stalker-backend
    container_name: stalker-backend
    restart: unless-stopped
    tty: true
    environment:
      - DATABASE_TYPE=postgres://
      - BASE_POSTGRES_URL=postgresql-1-postgresql-svc:5432
      - RETHINK_URL=rethinkdb-proxy
      - TESTING=True
      - FLASK_DEBUG=True
      - EMAIL_PASSWORD
      - LOCAL_HTTPS
      - MAIL_SUPPRESS_SEND=True
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5000:5000
      - 443:443
    networks:
      - backend-network
  ldap:
    container_name: ldap
    image: osixia/openldap
    tty: false
    ports:
      - "389:389"
      - "636:636"
    command: [--copy-service,  --loglevel, debug]
    volumes:
      - ./users.ldif:/container/service/slapd/assets/config/bootstrap/ldif/data.ldif
    environment:
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_BASE_DN=dc=daf,dc=test,dc=it
      - LDAP_REPLICATION_HOSTS=ldap://ldap.daf.test.it
      - LDAP_DOMAIN=daf.test.it
    networks:
      - backend-network
  phpldapadmin:
    container_name: phpldapadmin
    image: osixia/phpldapadmin
    tty: false
    ports:
      - "80:80"
    environment:
      - PHPLDAPADMIN_HTTPS="false"
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
    links:
      - ldap
    depends_on:
      - ldap
    networks:
      - backend-network
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - backend-network

volumes:
  postgres-data:
    driver: local
  rethink-data:
    driver: local
networks:
  backend-network:
    driver: bridge
