apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: stalker-backend
build:
  artifacts:
  - image: jjocram/stalker-backend
deploy:
  kubectl:
    manifests:
    - k8s/postgres-credentials.yml
    - k8s/postgres-deployment.yml
    - k8s/postgres-pv.yml
    - k8s/postgres-pvc.yml
    - k8s/postgres-service.yml
    - k8s/rethink-deployment.yml
    - k8s/rethink-pv.yml
    - k8s/rethink-pvc.yml
    - k8s/rethink-service.yml
    - k8s/stalker-deployment.yml
    - k8s/stalker-ingress.yml
    - k8s/stalker-service.yml
