apiVersion: v1
kind: Secret
metadata:
  name: credentials
type: Opaque
data:
  email_password: VHVsbGlvUnVsZWdnaWE=
  postgres_password: cGFzc3dvcmQ=
  app_id: MDU0OWY4OTQtNjRlZS00MGM1LTgwNDUtYjAwZjZkNzBlZDRm
  notification_auth_token: TURFMFlUZGpZbVF0WkRkaFpDMDBaV0ZqTFRsbU9UQXRNVGswT1dZMk5tVTNOR0k1