apiVersion: v1
kind: Service
metadata:
  name: postgresql-1-postgresql-svc
  labels:
    service: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432 #Porta default di postgres
  selector:
    service: postgres