apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rethink-pv-claim
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: rethink-pv
  storageClassName: standard