apiVersion: v1
kind: Service
metadata:
  name: rethinkdb-proxy
  labels:
    service: rethink
spec:
  type: ClusterIP
  ports:
    - port: 28015
      name: rethink-db
    - port: 8080
      name: rethink-dash
  selector:
    service: rethink
