apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: stalker-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: stalker-ip
    networking.gke.io/managed-certificates: stalker-certificate
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: stalker-backend
              servicePort: 80