apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "stalker-backend" # Nome del deployment
  namespace: "default"
  labels:
    app: "stalker-backend"
spec:
  replicas: 1 # Numero di pods che andranno ad eseguire l'immagine
  selector:
    matchLabels:
      app: "stalker-backend"
  template:
    metadata:
      labels:
        app: "stalker-backend"
    spec:
      containers:
        - name: "stalker-backend"
          image: "jjocram/stalker-backend:0.5.2" # Repo da dove scaricare l'immagine docker
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_TYPE
              value: 'postgres://'
            - name: BASE_POSTGRES_URL
              value: 'postgresql-1-postgresql-svc:5432'
            - name: RETHINK_URL
              value: 'rethinkdb-proxy'
            - name: TESTING
              value: 'False'
            - name: FLASK_DEBUG
              value: 'False'
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: email_password
                  name: credentials
            - name: MAIL_SUPPRESS_SEND
              value: 'False'
            - name: POSTGRES_USER
              value: 'postgres'
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgres_password
                  name: credentials
            - name: APP_ID
              valueFrom:
                secretKeyRef:
                  key: app_id
                  name: credentials
            - name: NOTIFICATION_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  key: notification_auth_token
                  name: credentials
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  key: cloud_name
                  name: cloudinary-credentials
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  key: api_key
                  name: cloudinary-credentials
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  key: api_secret
                  name: cloudinary-credentials
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 3
